// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Task1_VerticalSlice_ShopFlow.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260830114038_SeedProducts2")]
    partial class SeedProducts2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<int>("Cartid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cartid"));

                    b.HasKey("Cartid");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.HasKey("OrderID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("Cartid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("Cartid");

                    b.HasIndex("OrderID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Name = "Laptop",
                            Price = 10000m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductID = 2,
                            Name = "Mouse",
                            Price = 200m,
                            Quantity = 3
                        },
                        new
                        {
                            ProductID = 3,
                            Name = "Keyboard",
                            Price = 200m,
                            Quantity = 3
                        },
                        new
                        {
                            ProductID = 4,
                            Name = "Monitor",
                            Price = 1000m,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("Cartid");

                    b.HasOne("Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
